# Generated by Django 4.1.3 on 2023-01-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataBase',
        ),
    ]
